# Generated by Django 4.2.13 on 2024-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='reply_delay',
            field=models.IntegerField(default=60),
        ),
    ]
