# Generated by Django 4.2.13 on 2024-07-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='context',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
