# Generated by Django 4.2.13 on 2024-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_created_at_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
